const { chromium } = require('/Users/shmy/.npm/_npx/9833c18b2d85bc59/node_modules/playwright');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page = await browser.newPage({viewport:{width:1280,height:800}});
  const errors=[];
  page.on('pageerror',e=>errors.push(String(e)));
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
  page.on('response',r=>{if(r.status()>=400) errors.push(`${r.status()} ${r.url()}`);});
  await page.goto('http://127.0.0.1:8080/prototype/',{waitUntil:'networkidle'});
  await page.waitForTimeout(4000);
  const state=await page.evaluate(()=>({text:document.body.innerText,model:{r:BlackHoleShaderDemoApp.model.r,p:BlackHoleShaderDemoApp.model.p,yaw:BlackHoleShaderDemoApp.model.cameraYaw.getValue(),inclination:BlackHoleShaderDemoApp.model.orbitInclination.getValue()},canvas:document.querySelector('canvas').getBoundingClientRect().toJSON()}));
  await page.screenshot({path:'verification/rendered.png'});
  await page.keyboard.press('Space');
  const noPanelsAfterSpace=await page.evaluate(()=>document.body.innerText.trim()==='');
  await page.mouse.move(640,400);
  await page.mouse.wheel(0,400);
  await page.waitForTimeout(500);
  const fartherRadius=await page.evaluate(()=>BlackHoleShaderDemoApp.model.r);
  await page.screenshot({path:'verification/farther.png'});
  await page.mouse.down();
  await page.mouse.move(700,420,{steps:5});
  await page.mouse.up();
  const draggedYaw=await page.evaluate(()=>BlackHoleShaderDemoApp.model.cameraYaw.getValue());
  await page.locator('#camera_view').focus();
  await page.keyboard.press('ArrowUp');
  const inclination=await page.evaluate(()=>BlackHoleShaderDemoApp.model.orbitInclination.getValue());
  const timing=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let last;function step(t){if(last!==undefined)samples.push(t-last);last=t;if(samples.length===30){samples.sort((a,b)=>a-b);resolve({median:samples[15],p95:samples[28]});}else requestAnimationFrame(step)}requestAnimationFrame(step)}));
  const checks={noPanelsAfterSpace,scrollMovesOut:fartherRadius>state.model.r,dragChangesView:draggedYaw!==state.model.yaw,keyboardChangesInclination:inclination>state.model.inclination};
  const result={errors,state,checks,timing,browser:await browser.version(),fartherRadius,draggedYaw};
  console.log(JSON.stringify(result,null,2));
  fs.writeFileSync('verification/browser-result.json',JSON.stringify(result,null,2));
  await browser.close();
  if(errors.length || Object.values(checks).some(v=>!v)) process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
